[package]
authors = ["Jeff Muizelaar <jrmuizel@gmail.com>"]
edition = "2018"
name = "raqote"
version = "0.7.5-alpha.0"
description = "2D graphics library"
license = "BSD-3-Clause"
repository = "https://github.com/jrmuizel/raqote"
documentation = "https://docs.rs/raqote"
readme = "README.md"
keywords = ["2d", "graphics"]
categories = ["graphics"]

[dependencies]
euclid = "0.20"
font-kit = { version = "0.4", optional = true }
lyon_geom = "0.14"
png = "0.15"
typed-arena = "1.4.1"
sw-composite = "0.7.2"

[features]
default = ["text"]
text = ["font-kit"]
