[package]
authors = ["Jeff Muizelaar <jrmuizel@gmail.com>"]
edition = "2018"
name = "raqote"
version = "0.5.0"
description = "2D graphics library"
license = "BSD-3-Clause"
repository = "https://github.com/jrmuizel/raqote"
documentation = "https://docs.rs/raqote"
readme = "README.md"
keywords = ["2d", "graphics"]

[dependencies]
euclid = "0.19.8"
font-kit = { version = "0.3.0", optional = true }
lyon_geom = "0.12.6"
png = "0.14.0"
typed-arena = "1.4.1"
sw-composite = "0.5.10"

[features]
default = ["text"]
text = ["font-kit"]
